version: 2
registries:
  maven-repository-maven-zkoss-org-repo-zk-ee:
    type: maven-repository
    url: https://maven.zkoss.org/repo/zk/ee
    username: ville-noumea
    password: "${{secrets.MAVEN_REPOSITORY_MAVEN_ZKOSS_ORG_REPO_ZK_EE_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "15:00"
    timezone: Pacific/Noumea
  open-pull-requests-limit: 10
  rebase-strategy: disabled
  registries:
  - maven-repository-maven-zkoss-org-repo-zk-ee
