language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: pvsD2h41QYGKf/vsQDlZ/EkQxi5LeaS4pixDBwCoILZ47yr25iMA7Vt/VGQOEAZkLtAOoa3157A71KFXquJTGkASWkcLaEmIllCJDaZHgDnTBfqURYnEVAjBHDAAqXDDUNCDf76XevXYXkmiUaNB5C+DpQEFAbCLQyexlvFAB2vDaKuzRqmtuVaH8XCbuolZ9UN8nI3IyVAm//Wj9jPBPNKwjOP4HrJ98MXLUtyEaIJHzHcVHpOJh+zl5TSZYmTKxaeDnbR2XRNXFinK2bFliYQkm2pd1iB7lP1/6tdFpcwRp2raqJxFErknglGDx1P7mf+4l9tKm79boJ2WeRMANdmMcLXIfLZ8zdkjWtnmcbR2yadgqRkO+Yblrk55/fXbOFVLkSeSIY6x9cMvv+sHGMz9VWw6zsrCxOR9k8aogzQ2E2xtuUBhwYaOXY+bwAVALKH9Ug7xXsk2+c6kFS9r+0FRihS6PueT5wsZCu3WXQ7v7jYMUn0OMZ34rE7bG3Cwh4lVpaempicYHSto5htGZs9IfUWcNsMfhzpr81/O4s4x8aYSlqgZlRoIgf502OviAl8lLgzSKo9pnlgdnVKE2FkHBtl2heveIS0mIk72cKi/llCFMRojOJTCew0bXCEp1Quk3dn42/E3dcVYDmGLhu6j3sPWPAnZ7qH2b0EXBmM=
  - secure: PDTqUpVDrecUhOQxDjs5CuPwDwrFl/iUieQerSeMCVzv0+ATQErKzV3DTkOfGuBBPR/0bYHxCDtZtScLkX6xiWTMJlsmbBlMajgp0E/cQ9P1bTw19iSUq4Q9718YTTWc/YPkIMO088zesqMtyq7Vo9W9eTHZTMc+/xlFrLJZIB3dMZxIBbp2Rw2k4aEIi5UmqG+TLjDCYRCs719TsgoUWphX8S216NX9F2LByzEofcnVT5XZ1yMz1WaJRMsE1c85qS+GWRsvhLXEFEqbumTljALrSZuBE5Hp5N59noi7PW6mwmfdy/BuCx6poKfusmbTrmhzIZ/+RGjV1juFrcKrRJV9fSLAE6FaWoWr1M2OwKSFrx8uEYEkzxJuolgvy15PGGIYpnPq/boXNCfn4z2PRK0Gdby53gNelOHeZHlaFMcmEDqI9l8QNbyvbb15mjw54ngqzkJtHxoF9G1YPsWxLnXK3w5k+auoMRxg/nrFoa0eI7Yu99eYka/GuGeTemBR7v/j7COjRkDa6mecfExwefGu5ekXOUc0XDmb55bWOyfvZjhVC/m25CZTP9YkLIBtPRjIxTLr/pqWPoLv4fYtOxKPIhIPP3SKve4WmNtkgZjpN3ZCA+4FTcpMxSM2YTDWlqzJaMUC//h6bmS14Di0O8n7FTKdx00hdxagUQzNlHY=
before_install:
- export TZ=Pacific/Noumea
install: mvn clean install -DSkipTests=true -Dmaven.javadoc.skip=true -DcreateChecksum=true
  versioneye:update
before_deploy:
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- export RELEASE_PKG_MD5_FILE=$(ls target/*.jar.md5)
- export RELEASE_PKG_SHA_FILE=$(ls target/*.jar.sha1)
- echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE
  to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: IToV6Z31e3sVtVXk76T483PtsC603ybPAyE1yaWsb2hk4QKQIxDmGTOBtVeDYHJpzBBaugSv6+pKrcS9kwpeaKlpxTww9uSX4mdoUELwjh5TNap7NNEYfhMZCnXEDeZTH4DyLi/KoXl4pd+Gq4cdZcHaa0sOL9Tsv+2cPv/rh6ofUpCXjcSlkBjcPDiLYTA9y3x3klQRJe26tLRzdJyoy9Ko7Raf+5gEVkpRT9k8szL+ktuOtxJMSadN+nblBTTEvy52cCrPHC/XAZwaVawb1jSAyAgiZAlU3k/INESWIIpECjfUW5sPSciaWBlcfrxkw4gterrLAthoXx5r8HmuTDkqMUTwvsJOurDp7H70buuKPFELGYgSXDIgB4isiTWFQtCaLeLFcFJlv+WuMi1YkeMd2G9f/UowJ39+FKxAGN90KqQnh7zju9lny+WZNOlKY29fGTPUnwPQ3dtCNbXP5+yxIcSPVm+ywO1r1MvU/bdBFL/VNxvjQkrpZ2DprV2/T3Fj8qbd05MAQ04DmRikKB6hUyEawpp1udltxRjbrFFR5OPAMy3XJl0O4zYM9FXGlLSCc8CW6m+OpKg3irj2vfS1Z1U5P3dGGbGY1bCGGUN6YuIkwZv+bH7OtQCICav5LAGb37DzKf9CWao+j7SWvLhr3kUDU1Iz12jloKyXXgE=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/webapps-shortcuts-izpack
notifications:
  slack:
    secure: q3w2MsMuQ06clkV2Vd87aAcFdcnMaYY3pfiin19wAxRvcUt+EyxWk6+/B2fv0zvMASYHqR9xDULOAQbqlFWOsw4aJMmSVJ8SYfwHlpaLRXl3wSYX67XAJqi7Hv7t06rBCRDuD8pFme/8b/fBsMvjcCGlm1eLU5XQ5cVpniSVYJxFEenaJKYZch0TxDdvIKIbin9vGULQyBXN5+1yy04lyC9TEM8Tv+A0iGVhXHruOIERQ8l9DFwln8K/9vtVd8HuzRv1KGKSYxPfER5YBNI2pU/FJ0mjHFxDaqWd2l1mI+Egce1NvjC2dG3LDiZjbFLUJLmJ+89buyxb29LEl7PpN7oDBdb5ZQSSSzd4b/3Wv0P+3cHu8Uj8TgSfwHwm3//z0PuVGn61Pc65MpoEvutbbAyiZq35L5pnHqWSvGxhpadQ+7N+qe2N0y4WGewvnGJ4ZtO8//xAuWMVRSxsgLLyTRIfn859tlqy0eZuW3jaJuxgJJIcozAVSf4LUA56kL21r6DHFMfv4MgzP2PIClRdJFLToa/ykdXzeOAHnlO1ogoilXTvFVRDXjr2i7V1Wp4iKfqwUzS2CjSfxnvBtefFpB7vwWxaRtcS41yR9tkcA2Xp15vhMb4UgZ2cITYNsk/FkkntEIqvRrbeRgHLJIiXqFUA2yTDH82rLXqsMbe4LaM=
